name: Nightly

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
      
      - name: update Atmosphere-libs
        run: |
          pushd Atmosphere-libs
          git fetch --all
          git reset --hard origin/master
          popd
      
      - name: Build
        run: make -j8 PREFIX="ccache aarch64-none-elf-"

      - name: Install libnx master & Retry build
        if: ${{ failure() }}
        run: |
          pushd /tmp
          git clone https://github.com/switchbrew/libnx
          cd libnx
          make -j8 PREFIX="ccache aarch64-none-elf-"
          make install
          popd
          make -j8 PREFIX="ccache aarch64-none-elf-"

      - name: Upload built files
        uses: actions/upload-artifact@v3
        with:
          name: sdcard
          path: out/sd

      - name: Upload elf file
        uses: actions/upload-artifact@v3
        with:
          name: ldn_mitm.elf
          path: ldn_mitm/ldn_mitm.elf

      - name: Upload elf file
        uses: actions/upload-artifact@v3
        with:
          name: ldn_mitm.elf
          path: overlay/overlay.elf
